metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_corporate
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - LQDE.L
      - LQDG.L
      - IEAC.L
      - CORP.L
      - LQD
      - VCIT
      - VCSH
      - VCLT
      - VTC
      - IGIB
      - IGSB
      - IGLB
      - SLQD
      - USIG
      - CORP
      - SPBO
      - SPIB
      - SPSB
      - LQDH
      - LQDB
      - LQDW
      - LQIG
      - IGBH
      - IGEB
      - SCYB
      - PFIG
      - FLOT
      - FLRN
      - SRLN
      - BKLN
      - FTSL
      - JNK
      - HYG
      - SJNK
      - SHYG
      - HYLB
      - USHY
      - HYS
      - PHB
      - ANGL
      - FALN
      - HYGH
      - GHYG
      - HYEM
      - EMHY
      - JHCB
      - HYGW
      - ICVT
      - FCVT
      - CWB
      - PGHY
      - CLOA
      - CLOI
      - CLOZ
      - CLOX
      - JAAA
      - JBBB
      - BSCQ
      - BSCR
      - BSCS
      - BSCT
      - BSCU
      - BSCV
      - BSCW
      - BSCX
      - BSCY
      - BSCZ
      - BSJQ
      - BSJR
      - BSJS
      - BSJT
      - BSJU
      - BSJV
      - BSJW
      - BSJX
      - IBDR
      - IBDS
      - IBDT
      - IBDU
      - IBDV
      - IBDW
      - IBDX
      - IBDY
      - IBDZ
      - IBHF
      - IBHG
      - IBHH
      - IBHI
      - IBHJ
      - IBHK
      - IBHL
      - SPLB
      - SPHY
      - SCHI
      - SCHJ
      - BBHY
      - BBBS
      - XCCC
      - XBB
      - HYLS
timeframes: ["1d"]

strategies: []
