metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_tips
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - ITPS.L
      - TI5G.L
      - TIP
      - SCHP
      - STIP
      - VTIP
      - LTPZ
      - TIPZ
      - TDTF
      - TDTT
      - SPIP
      - RINF
      - IVOL
      - DFIP
      - WIP
      - GTIP
      - STPZ
      - TIPX
      - RBIL
      - IBIC
      - IBIH
      - IBIK
      - IBCI.DE
      - IBCID.XD
      - XSTP-U.TO
      - CTIP.NE
      - ILB.AX
      - ILB.XA
      - UBIF.L
      - XTIP.L
      - XTIP.DE
      - INXG.L
      - INXG.MI
      - INXGL.XC
      - GILI.PA
      - XGII.MI
      - 2B7T.MU
      - XRUG.MU
      - LQDI
      - 4JZM.BE
      - 610001.KS
      - 610003.KS
      - BPRIX
      - BPRAX
      - BPRCX
      - BPLBX
      - ABNAX
      - ABNYX
      - ABTPX
      - ACITX
      - ACUYX
      - AIANX
      - AIAVX
      - APOIX
      - APISX
      - ATPIX
      - DIPIX
      - DIPSX
      - DIASX
      - FAIPX
      - FINPX
      - FADUX
      - FADWX
      - FICPX
      - FIPEX
      - FIPPX
      - FIDDX
      - FSPWX
      - TIIPX
      - TIILX
      - GSIPX
      - SWRSX
      - HIPIX
      - PIFPX
      - PIPIX
      - PBPPX
      - PRIPX
      - PRRIX
      - PRLPX
      - PRNPX
      - PARRX
      - PRTNX
      - PRTCX
      - PRRRX
      - VIPSX
      - VAIPX
      - VIPIX
      - DFAIX
      - IPBNX
      - LIPNX
      - PQTSX
      - DIHMAX
      - IRVH
      - XWIAX
      - RRFAX
      - PRAIX
      - 0P0000K8D3.L
      - 0P0001CO2M.L
      - 0P0001COEN.L
      - 0P0001COEO.L

timeframes: ["1d"]

strategies: []
