metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_high_yield
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - IHYG.L
      - SHYU.L
      - PDI
      - PDO
      - FRA
      - BKT
      - NCV
      - DSL
      - BTZ
      - NCZ
      - PDX
      - DLY
      - TBLD
      - MSIF
      - FTHY
      - BLW
      - SDHY
      - PPT
      - EFT
      - FINS
      - ARDC
      - MIN
      - ACV
      - MMT
      - MCR
      - FTF
      - PIM
      - XFLT
      - JHS
      - EVF
      - GCV
      - RSF
      - ACP
      - AVK
      - AWF
      - BGB
      - BGH
      - BGT
      - BGX
      - BHK
      - BIT
      - BRW
      - BSL
      - BWG
      - CCD
      - CCIF
      - CHI
      - CHW
      - CHY
      - CIF
      - CIK
      - DBL
      - DHF
      - DHY
      - EAD
      - ECF
      - EDF
      - EFR
      - EHI
      - ERC
      - EVG
      - EVV
      - FAX
      - FCO
      - FCT
      - GHY
      - HEQ
      - HERZ
      - HFRO
      - HIO
      - HIX
      - HYI
      - HYT
      - ISD
      - JFR
      - JGH
      - JMM
      - JQC
      - KIO
      - LGI
      - NHS
      - NMAI
      - PAI
      - PAXS
      - PCF
      - PCN
      - PFL
      - PFN
      - PGP
      - PHK
      - PTY
      - RCS
      - SABA
      - SCD
      - TEI
      - TSI
      - VBF
      - VGI
      - VLT
      - VVR
timeframes: ["1d"]

strategies: []
