metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_municipal
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - MUBD.L
      - MUBU.L
      - NAN
      - MUJ
      - MIY
      - MHD
      - MQY
      - MYI
      - MUA
      - MVT
      - MUC
      - MYD
      - MHN
      - MUE
      - MQT
      - MVF
      - FMN
      - NXP
      - VMO
      - NDMO
      - IIM
      - NMCO
      - VGM
      - VKQ
      - VCV
      - IQI
      - EVN
      - VKI
      - LEO
      - KTF
      - PMO
      - GBAB
      - RFMZ
      - PMM
      - OIA
      - RMMZ
      - RMM
      - EOT
      - VPV
      - VTN
      - MFM
      - ETX
      - CXE
      - CMU
      - RMI
      - RFM
      - DTF
      - CXH
      - CEV
      - AFB
      - BBN
      - BFK
      - BFZ
      - BHV
      - BKN
      - BLE
      - BMN
      - BNY
      - BTA
      - BTT
      - BYM
      - DMB
      - DSM
      - EIM
      - MHF
      - MMD
      - MMU
      - MPA
      - MYN
      - NAC
      - NAD
      - NAZ
      - NBB
      - NBH
      - NCA
      - NEA
      - NIM
      - NKX
      - NMI
      - NMS
      - NMT
      - NMZ
      - NNY
      - NOM
      - NPV
      - NQP
      - NRK
      - NUV
      - NUW
      - NVG
      - NXJ
      - NZF
      - PCQ
      - PML
      - PNI
      - SBI
      - VFL
      - MUB
      - VTEB
      - SHM
timeframes: ["1d"]

strategies: []
