metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_global
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - AGGH.L
      - VAGP.L
      - IGLA.L
      - FEMB
      - CGIB
      - FOPC
      - GXIG
      - JHLN
      - IAGG
      - RSSB
      - SLDR
      - USFI
      - VEMY
      - BNDX
      - BNDW
      - BREM
      - JEMB
      - JPIB
      - JPMB
      - LLDR
      - DFGP
      - DGCB
      - DFGX
      - DFSB
      - EBND
      - EMBD
      - EMB
      - EMTL
      - EMHC
      - EMCB
      - ELD
      - MLDR
      - BSV
      - CFIT
      - CGCB
      - CGHY
      - CCSB
      - CEMB
      - CMBS
      - CSHP
      - GNMA
      - GSIG
      - GSST
      - GTOC
      - GTOS
      - GTO
      - GVI
      - GRNB
      - HCRB
      - HBDC
      - JOJO
      - JLQD
      - JHCR
      - JHCP
      - JFLX
      - HYSA
      - HYGV
      - IBD
      - HYBB
      - HYDB
      - HYXF
      - IBCA
      - HYBI
      - HYBX
      - HYZD
      - HYUP
      - HYDW
      - KDRN
      - KHYB
      - KNRG
      - KORP
      - LDRC
      - LDRH
      - QLTA
      - QSIG
      - RDFI
      - RTRE
      - RSBY
      - RSBT
      - RSBA
      - SCIO
      - SCHZ
      - SDCP
      - SEIX
      - SHAG
      - SHYL
      - SKOR
      - SJCP
      - SLNZ
      - ULST
      - UNIY
      - VETZ
      - VCRB
      - VCRM
      - VGMS
      - SUSB
      - SUSC
      - STXT
      - APCB
      - CBON
timeframes: ["1d"]

strategies: []
