metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: commodities
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - SGLN.L
      - PHAU.L
      - SSLN.L
      - PHAG.L
      - IGLN.L
      - CRUD.L
      - BRNT.L
      - NGAS.L
      - CMOD.L
      - ICOM.L

timeframes: ["1d"]

strategies: []
