metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data
collections:
- name: stocks_dividend
  source: yfinance
  fees: 0.0005
  slippage: 0.0005
  symbols:
  - VHYL.L
  - WQDV.L
  - IDVY.L
  - IUKD.L
  - PG
  - PEP
  - MCD
  - XOM
  - CVX
  - VZ
  - ENB
  - BATS.L
timeframes:
- 1d
strategies: []
