metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data
collections:
- name: stocks_international
  source: yfinance
  fees: 0.0005
  slippage: 0.0005
  symbols:
  - RIO.L
  - BHP.L
  - TM
  - SONY
  - RY
timeframes:
- 1d
strategies: []
