metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
- name: stocks_international
  source: yfinance
  fees: 0.0005
  slippage: 0.0005
  symbols:
  - BHP.L
  - TM
  - SONY
  - RY
  - 9984.T
  - 8306.T
  - 8316.T
  - 8411.T
  - 9433.T
  - 9432.T
  - 9434.T
  - 7267.T
  - 8031.T
  - 8058.T
  - 8001.T
  - 8015.T
  - 8766.T
  - 6501.T
  - 6503.T
  - 6752.T
  - 6861.T
  - 7741.T
  - 7974.T
  - 6954.T
  - 6273.T
  - 6367.T
  - 7751.T
  - 6981.T
  - 9983.T
  - 4502.T
  - TD.TO
  - BNS.TO
  - BMO.TO
  - CM.TO
  - ENB.TO
  - TRP.TO
  - SU.TO
  - CNQ.TO
  - CNR.TO
  - CP.TO
  - BCE.TO
  - T.TO
  - RCI-B.TO
  - SHOP.TO
  - WCN.TO
  - FNV.TO
  - BAM.A.TO
  - BN.TO
  - BHP.AX
  - CBA.AX
  - CSL.AX
  - WBC.AX
  - NAB.AX
  - ANZ.AX
  - WOW.AX
  - WES.AX
  - MQG.AX
  - TLS.AX
  - GMG.AX
  - RIO.AX
  - WDS.AX
  - FMG.AX
  - STO.AX
  - NOVO-B.CO
  - MAERSK-B.CO
  - DANSKE.CO
  - ORSTED.CO
  - VWS.CO
  - CARL-B.CO
  - VOLV-B.ST
  - ERIC-B.ST
  - ATCO-A.ST
  - ALFA.ST
  - EQNR.OL
  - DNB.OL
  - NOKIA.HE
  - KNEBV.HE
  - NESTE.HE
  - ENEL.MI
  - ISP.MI
  - UCG.MI
  - G.MI
  - STMMI.MI
  - PRY.MI
  - LDO.MI
  - STLAM.MI
  - ABI.BR
  - UCB.BR
  - OMV.VI
  - RBI.VI
  - ERST.VI
  - CRH.IR
  - RYA.IR
  - KYGA.IR
  - D05.SI
  - O39.SI
  - U11.SI
  - OPAP.AT
  - OTE.AT
  - FPH.NZ
timeframes:
- 1d
strategies: []
