metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data
collections:
- name: traderfox_research_us
  source: yfinance
  fees: 0.0005
  slippage: 0.0005
  symbols:
  - TSM
  - JPM
  - BAC
  - WFC
  - GS
  - MS
  - C
  - USB
  - TFC
  - PNC
  - COF
  - AXP
  - BLK
  - SPGI
  - MCO
  - ICE
  - CME
  - NDAQ
  - CBOE
  - MSCI
  - TRV
  - PGR
  - ALL
  - AIG
  - MET
  - PRU
  - AFL
  - AMP
  - LNC
  - PFG
  - TMK
  - GL
  - RGA
  - CNO
  - V
  - MA
  - PYPL
  - SQ
  - FISV
  - FIS
  - ADP
  - PAYX
  - BR
  - FLT
  - WEX
  - GPN
  - TSS
  - JKHY
  - ACIW
  - QTWO
  - BILL
  - LC
  - UPST
  - AFRM
  - SOFI
  - HOOD
  - COIN
  - MSTR
  - SI
  - ALLY
  - CFG
  - KEY
  - FITB
  - HBAN
  - RF
  - MTB
  - STI
  - ZION
  - PBCT
  - CMA
  - WAL
  - EWBC
  - PACW
  - COLB
  - OZK
  - FHN
  - BKU
  - ONB
  - UMBF
  - BANF
  - WAFD
  - IBOC
  - OPFI
  - RBRK
  - KRMN
  - LTH
  - BJ
  - AU
  - WELL
  - T
  - ED
  - KR
  - AEP
  - SCHW
  - IBM
  - RTX
  - BMI
  - GME
  - LUMN
  - MLI
  - PAGS
  - MRK
  - WMT
  - F
  - KO
  - PAY
  - SG
  - NVR
  - AA
  - CACI
  - MLR
  - GRMN
  - FIX
  - FDX
  - ELF
  - DAL
  - CRM
  - CMI
  - BH
  - ARIS
  - CCJ
  - LRN
  - CMG
  - APH
  - LLY
  - BAH
  - SCCO
  - TNC
  - FCX
  - NOC
  - LMT
  - TDW
  - PWR
  - FOR
  - RSG
  - MMC
  - BRK.A
  - DT
  - PR
  - CRC
  - COR
  - VEEV
  - TDY
  - ITT
  - ATR
  - AIT
  - AWI
  - DCI
  - PH
  - GWW
  - ALG
  - NRG
  - UBS
  - STM
  - AMS
  - JNJ
  - PFE
  - UNH
  - ABBV
  - TMO
  - DHR
  - ABT
  - BMY
  - GILD
  - AMGN
  - BIIB
  - REGN
  - VRTX
  - ZTS
  - CVS
  - CI
  - HUM
  - ANTM
  - MCK
  - ABC
  - CAH
  - WBA
  - MDT
  - ISRG
  - SYK
  - BSX
  - BDX
  - EW
  - ZBH
  - BAX
  - HOLX
  - IDXX
  - ALGN
  - DXCM
  - RMD
  - ILMN
  - MKTX
  - TDOC
  - DOCU
  - HIMS
  - ONEM
  - AMWL
  - OSCR
  - MRNA
  - BNTX
  - NVAX
  - OCGN
  - INO
  - SRNE
  - VXRT
  - GEVO
  - CODX
  - QDEL
  - DVAX
  - IOVA
  - TXMD
  - CERC
  - ADVM
  - DARE
  - KERN
  - XERS
  - ATOS
  - CTMX
  - PROG
  - ADMA
  - SESN
  - AXSM
  - PTCT
  - ALNY
  - BMRN
  - TECH
  - RARE
  - FOLD
  - BLUE
  - CRSP
  - EDIT
  - NTLA
  - BEAM
  - VERV
  - SGMO
  - FATE
  - BLFS
  - CDNA
  - ARCT
  - DMTK
  - VCYT
  - PACB
  - NVTA
  - TWST
  - NTRA
  - GH
  - CDXS
  - AGIO
  - ARQL
  - APLS
  - AVXL
  - CBIO
  - ACAD
  - HZNP
  - JAZZ
  - UTHR
  - NBIX
  - SAGE
  - INCY
  - EXEL
  - BGNE
  - ZLAB
  - RGNX
  - IMMU
  - SGEN
  - BPMC
  - MRUS
  - CPRX
  - VCEL
  - CAPR
  - MEDP
  - VKTX
  - ACLX
  - NVCR
  - TMDX
  - VECO
  - BHVN
  - AOSL
  - CELH
  - SEZL
  - ALLO
  - PRAX
  - RCAT
  - OTLK
  - CENX
  - PSNL
  - NSIT
  - CHRS
  - SIGA
  - ACIU
  - PERI
  - STNE
  - LILA
  - ALTI
  - INDV
  - CEVA
  - SPNS
  - CFB
  - LWAY
  - CRBP
  - FEIM
  - PLAB
  - DSP
  - PNTG
  - IDYA
  - ENTG
  - RMBS
  - TSAT
  - HALO
  - OMER
  - ADUS
  - LMAT
  - FELE
  - APOG
  - CRL
  - CBLL
  - COOP
  - CHDN
  - ENSG
  - DGX
  - KYMR
  - CSTL
  - TREE
  - SNEX
  - CCB
  - OSIS
  - PLMR
  - CASY
  - LECO
  - HLNE
  - UFPT
  - ERIE
  - MOH
  - ITIC
  - PIPR
  - FCNCA
  - VIRT
  - NARI
  - ALGT
  - RKLB
  - IONQ
  - FUTU
  - BABA
  - ULTA
  - DOCS
  - UNFI
  - BIDU
  - ROKU
  - TTAN
  - LNTH
  - TTMI
  - BYRN
  - GRAB
  - EH
  - ASTS
  - DOCN
  - SMPL
  - PGY
  - FRHC
  - ETON
  - AKRO
  - MRCY
  - RDNT
  - ARDX
  - AMAT
  - TTD
  - DKNG
  - DASH
  - TEVA
  - DBX
  - CROX
  - CORT
  - AXON
  - TXRH
  - ABNB
  - NET
  - TZOO
  - EXLS
  - SOUN
  - CRWD
  - IBKR
  - AHCO
  - ENVX
  - APPF
  - TLN
  - FLEX
  - TEM
  - ME
  - EBAY
  - AUR
  - TATT
  - SPSC
  - ALAB
  - PRCH
  - SYM
  - LRCX
  - APLT
  - MARA
  - RGTI
  - ZI
  - SNOW
  - RDVT
  - CDNS
  - SMWB
  - DTSS
  - TSLA
  - UFPI
  - AVGO
  - VRNS
  - MSFT
  - ARM
  - IMNM
  - GERN
  - VTSI
  - LUNR
  - MELI
  - APPN
  - ALVO
  - MORN
  - QCOM
  - NTNX
  - KLAC
  - QLYS
  - MAR
  - PCAR
  - KRUS
  - PDD
  - XMTR
  - GCT
  - LFMD
  - BKNG
  - APGE
  - ROAD
  - APP
  - ARVN
  - TNDM
  - CGON
  - ADPT
  - TRUP
  - CWST
  - CALX
  - FSLR
  - PI
  - KAI
  - HWKN
  - INTU
  - PSMT
  - FCFS
  - MGRC
  - COKE
  - DORM
  - LOPE
  - COST
  - CVCO
  - HESM
  - ANSS
  - IPAR
  - CSWI
  - YELP
  - ATRO
  - AIOT
  - ARQT
  - INTA
  - ATAT
  - MTSR
  - ANGO
  - RR
  - ALHC
  - SLNO
  - PDEX
  - RGLD
  - OPOF
  - SENEB
  - ORLY
  - CRWV
  - RYTM
  - TARS
  - WLFC
  - FTAI
  - AMSC
  - AAPL
  - GOOGL
  - GOOG
  - AMZN
  - META
  - NFLX
  - NVDA
  - AMD
  - INTC
  - TXN
  - MU
  - MRVL
  - ADI
  - MCHP
  - ADBE
  - ORCL
  - ACN
  - NOW
  - CSCO
  - VMW
  - TEAM
  - DDOG
  - ZS
  - OKTA
  - SPLK
  - WDAY
  - ZM
  - TWLO
  - FSLY
  - BOX
  - WORK
  - UBER
  - LYFT
  - RBLX
  - PINS
  - SNAP
  - TWTR
  - SHOP
  - SPOT
  - ESTC
  - MDB
  - PLTR
  - AI
  - C3AI
  - PATH
  - SMCI
  - DELL
  - HPQ
  - HPE
  - NTAP
  - WDC
  - STX
  - PSTG
  - VRSN
  - AKAM
  - SNPS
  - ADSK
  - FTNT
  - PANW
  - CHKP
  - CYBR
  - TENB
  - RPD
  - MIME
  - FEYE
  - PFPT
  - EVBG
  - CGNX
  - TER
  - COHU
  - FORM
  - MKSI
  - ONTO
  - ACLS
  - UCTT
  - NVMI
  - ICHR
  - CRUS
  - SWKS
  - QRVO
  - MPWR
  - MTSI
  - SLAB
  - SITM
  - DIOD
  - WOLF
  - AMBA
  - ALGM
  - SMTC
  - POWI
  - VICR
  - DXPE
  - CFLT
  - CEG
  - CECO
  - ATEC
  - MNDY
timeframes:
- 1d
strategies: []
