metric: sortino
engine: pybroker
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_corporate
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - LQDE.L
      - LQDG.L
      - IEAC.L
      - CORP.L

timeframes: ["1d"]

strategies: []
